### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by ksiuda93** [selcukusta/redis-sentinel-with-haproxy#1]
Hey, 

Great job with this project ! Unfortunately, I've found one issue in redis Dockerfile, you have to add following line: `chmod a+x /etc/redis/redis-entrypoint.sh` because you still getting permission denied during image building.

**Comment by selcukusta** [comment]
Hi @ksiuda93, thank you for your help! Solved with [this commit](https://github.com/selcukusta/redis-sentinel-with-haproxy/commit/5c8073703803707d05cbd411726932e15ea17f41).
